// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb-itai/dal/model"
)

func newEmail(db *gorm.DB, opts ...gen.DOOption) email {
	_email := email{}

	_email.emailDo.UseDB(db, opts...)
	_email.emailDo.UseModel(&model.Email{})

	tableName := _email.emailDo.TableName()
	_email.ALL = field.NewAsterisk(tableName)
	_email.ID = field.NewInt64(tableName, "id")
	_email.Host = field.NewString(tableName, "host")
	_email.Username = field.NewString(tableName, "username")
	_email.Password = field.NewString(tableName, "password")
	_email.Enable = field.NewBool(tableName, "enable")

	_email.fillFieldMap()

	return _email
}

type email struct {
	emailDo emailDo

	ALL      field.Asterisk
	ID       field.Int64
	Host     field.String
	Username field.String
	Password field.String
	Enable   field.Bool

	fieldMap map[string]field.Expr
}

func (e email) Table(newTableName string) *email {
	e.emailDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e email) As(alias string) *email {
	e.emailDo.DO = *(e.emailDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *email) updateTableName(table string) *email {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.Host = field.NewString(table, "host")
	e.Username = field.NewString(table, "username")
	e.Password = field.NewString(table, "password")
	e.Enable = field.NewBool(table, "enable")

	e.fillFieldMap()

	return e
}

func (e *email) WithContext(ctx context.Context) *emailDo { return e.emailDo.WithContext(ctx) }

func (e email) TableName() string { return e.emailDo.TableName() }

func (e email) Alias() string { return e.emailDo.Alias() }

func (e email) Columns(cols ...field.Expr) gen.Columns { return e.emailDo.Columns(cols...) }

func (e *email) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *email) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["id"] = e.ID
	e.fieldMap["host"] = e.Host
	e.fieldMap["username"] = e.Username
	e.fieldMap["password"] = e.Password
	e.fieldMap["enable"] = e.Enable
}

func (e email) clone(db *gorm.DB) email {
	e.emailDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e email) replaceDB(db *gorm.DB) email {
	e.emailDo.ReplaceDB(db)
	return e
}

type emailDo struct{ gen.DO }

func (e emailDo) Debug() *emailDo {
	return e.withDO(e.DO.Debug())
}

func (e emailDo) WithContext(ctx context.Context) *emailDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emailDo) ReadDB() *emailDo {
	return e.Clauses(dbresolver.Read)
}

func (e emailDo) WriteDB() *emailDo {
	return e.Clauses(dbresolver.Write)
}

func (e emailDo) Session(config *gorm.Session) *emailDo {
	return e.withDO(e.DO.Session(config))
}

func (e emailDo) Clauses(conds ...clause.Expression) *emailDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emailDo) Returning(value interface{}, columns ...string) *emailDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emailDo) Not(conds ...gen.Condition) *emailDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emailDo) Or(conds ...gen.Condition) *emailDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emailDo) Select(conds ...field.Expr) *emailDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emailDo) Where(conds ...gen.Condition) *emailDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emailDo) Order(conds ...field.Expr) *emailDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emailDo) Distinct(cols ...field.Expr) *emailDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emailDo) Omit(cols ...field.Expr) *emailDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emailDo) Join(table schema.Tabler, on ...field.Expr) *emailDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emailDo) LeftJoin(table schema.Tabler, on ...field.Expr) *emailDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emailDo) RightJoin(table schema.Tabler, on ...field.Expr) *emailDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emailDo) Group(cols ...field.Expr) *emailDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emailDo) Having(conds ...gen.Condition) *emailDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emailDo) Limit(limit int) *emailDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emailDo) Offset(offset int) *emailDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *emailDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emailDo) Unscoped() *emailDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emailDo) Create(values ...*model.Email) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emailDo) CreateInBatches(values []*model.Email, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emailDo) Save(values ...*model.Email) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emailDo) First() (*model.Email, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Email), nil
	}
}

func (e emailDo) Take() (*model.Email, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Email), nil
	}
}

func (e emailDo) Last() (*model.Email, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Email), nil
	}
}

func (e emailDo) Find() ([]*model.Email, error) {
	result, err := e.DO.Find()
	return result.([]*model.Email), err
}

func (e emailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Email, err error) {
	buf := make([]*model.Email, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emailDo) FindInBatches(result *[]*model.Email, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emailDo) Attrs(attrs ...field.AssignExpr) *emailDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emailDo) Assign(attrs ...field.AssignExpr) *emailDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emailDo) Joins(fields ...field.RelationField) *emailDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emailDo) Preload(fields ...field.RelationField) *emailDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emailDo) FirstOrInit() (*model.Email, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Email), nil
	}
}

func (e emailDo) FirstOrCreate() (*model.Email, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Email), nil
	}
}

func (e emailDo) FindByPage(offset int, limit int) (result []*model.Email, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emailDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emailDo) Delete(models ...*model.Email) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emailDo) withDO(do gen.Dao) *emailDo {
	e.DO = *do.(*gen.DO)
	return e
}
