// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb-itai/dal/model"
)

func newEvent(db *gorm.DB, opts ...gen.DOOption) event {
	_event := event{}

	_event.eventDo.UseDB(db, opts...)
	_event.eventDo.UseModel(&model.Event{})

	tableName := _event.eventDo.TableName()
	_event.ALL = field.NewAsterisk(tableName)
	_event.ID = field.NewInt64(tableName, "id")
	_event.MinionID = field.NewInt64(tableName, "minion_id")
	_event.Inet = field.NewString(tableName, "inet")
	_event.Subject = field.NewString(tableName, "subject")
	_event.RemoteAddr = field.NewString(tableName, "remote_addr")
	_event.RemotePort = field.NewInt(tableName, "remote_port")
	_event.FromCode = field.NewString(tableName, "from_code")
	_event.Typeof = field.NewString(tableName, "typeof")
	_event.User = field.NewString(tableName, "user")
	_event.Auth = field.NewString(tableName, "auth")
	_event.Msg = field.NewString(tableName, "msg")
	_event.Error = field.NewString(tableName, "error")
	_event.Region = field.NewString(tableName, "region")
	_event.Level = field.NewField(tableName, "level")
	_event.HaveRead = field.NewBool(tableName, "have_read")
	_event.SendAlert = field.NewBool(tableName, "send_alert")
	_event.Secret = field.NewString(tableName, "secret")
	_event.OccurAt = field.NewTime(tableName, "occur_at")
	_event.CreatedAt = field.NewTime(tableName, "created_at")

	_event.fillFieldMap()

	return _event
}

type event struct {
	eventDo eventDo

	ALL        field.Asterisk
	ID         field.Int64
	MinionID   field.Int64
	Inet       field.String
	Subject    field.String
	RemoteAddr field.String
	RemotePort field.Int
	FromCode   field.String
	Typeof     field.String
	User       field.String
	Auth       field.String
	Msg        field.String
	Error      field.String
	Region     field.String
	Level      field.Field
	HaveRead   field.Bool
	SendAlert  field.Bool
	Secret     field.String
	OccurAt    field.Time
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (e event) Table(newTableName string) *event {
	e.eventDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e event) As(alias string) *event {
	e.eventDo.DO = *(e.eventDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *event) updateTableName(table string) *event {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.MinionID = field.NewInt64(table, "minion_id")
	e.Inet = field.NewString(table, "inet")
	e.Subject = field.NewString(table, "subject")
	e.RemoteAddr = field.NewString(table, "remote_addr")
	e.RemotePort = field.NewInt(table, "remote_port")
	e.FromCode = field.NewString(table, "from_code")
	e.Typeof = field.NewString(table, "typeof")
	e.User = field.NewString(table, "user")
	e.Auth = field.NewString(table, "auth")
	e.Msg = field.NewString(table, "msg")
	e.Error = field.NewString(table, "error")
	e.Region = field.NewString(table, "region")
	e.Level = field.NewField(table, "level")
	e.HaveRead = field.NewBool(table, "have_read")
	e.SendAlert = field.NewBool(table, "send_alert")
	e.Secret = field.NewString(table, "secret")
	e.OccurAt = field.NewTime(table, "occur_at")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *event) WithContext(ctx context.Context) *eventDo { return e.eventDo.WithContext(ctx) }

func (e event) TableName() string { return e.eventDo.TableName() }

func (e event) Alias() string { return e.eventDo.Alias() }

func (e event) Columns(cols ...field.Expr) gen.Columns { return e.eventDo.Columns(cols...) }

func (e *event) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *event) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 19)
	e.fieldMap["id"] = e.ID
	e.fieldMap["minion_id"] = e.MinionID
	e.fieldMap["inet"] = e.Inet
	e.fieldMap["subject"] = e.Subject
	e.fieldMap["remote_addr"] = e.RemoteAddr
	e.fieldMap["remote_port"] = e.RemotePort
	e.fieldMap["from_code"] = e.FromCode
	e.fieldMap["typeof"] = e.Typeof
	e.fieldMap["user"] = e.User
	e.fieldMap["auth"] = e.Auth
	e.fieldMap["msg"] = e.Msg
	e.fieldMap["error"] = e.Error
	e.fieldMap["region"] = e.Region
	e.fieldMap["level"] = e.Level
	e.fieldMap["have_read"] = e.HaveRead
	e.fieldMap["send_alert"] = e.SendAlert
	e.fieldMap["secret"] = e.Secret
	e.fieldMap["occur_at"] = e.OccurAt
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e event) clone(db *gorm.DB) event {
	e.eventDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e event) replaceDB(db *gorm.DB) event {
	e.eventDo.ReplaceDB(db)
	return e
}

type eventDo struct{ gen.DO }

func (e eventDo) Debug() *eventDo {
	return e.withDO(e.DO.Debug())
}

func (e eventDo) WithContext(ctx context.Context) *eventDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventDo) ReadDB() *eventDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventDo) WriteDB() *eventDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventDo) Session(config *gorm.Session) *eventDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventDo) Clauses(conds ...clause.Expression) *eventDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventDo) Returning(value interface{}, columns ...string) *eventDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventDo) Not(conds ...gen.Condition) *eventDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventDo) Or(conds ...gen.Condition) *eventDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventDo) Select(conds ...field.Expr) *eventDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventDo) Where(conds ...gen.Condition) *eventDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventDo) Order(conds ...field.Expr) *eventDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventDo) Distinct(cols ...field.Expr) *eventDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventDo) Omit(cols ...field.Expr) *eventDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventDo) Join(table schema.Tabler, on ...field.Expr) *eventDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *eventDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventDo) RightJoin(table schema.Tabler, on ...field.Expr) *eventDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventDo) Group(cols ...field.Expr) *eventDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventDo) Having(conds ...gen.Condition) *eventDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventDo) Limit(limit int) *eventDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventDo) Offset(offset int) *eventDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *eventDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventDo) Unscoped() *eventDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventDo) Create(values ...*model.Event) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventDo) CreateInBatches(values []*model.Event, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventDo) Save(values ...*model.Event) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventDo) First() (*model.Event, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Event), nil
	}
}

func (e eventDo) Take() (*model.Event, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Event), nil
	}
}

func (e eventDo) Last() (*model.Event, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Event), nil
	}
}

func (e eventDo) Find() ([]*model.Event, error) {
	result, err := e.DO.Find()
	return result.([]*model.Event), err
}

func (e eventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Event, err error) {
	buf := make([]*model.Event, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventDo) FindInBatches(result *[]*model.Event, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventDo) Attrs(attrs ...field.AssignExpr) *eventDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventDo) Assign(attrs ...field.AssignExpr) *eventDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventDo) Joins(fields ...field.RelationField) *eventDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventDo) Preload(fields ...field.RelationField) *eventDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventDo) FirstOrInit() (*model.Event, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Event), nil
	}
}

func (e eventDo) FirstOrCreate() (*model.Event, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Event), nil
	}
}

func (e eventDo) FindByPage(offset int, limit int) (result []*model.Event, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventDo) Delete(models ...*model.Event) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventDo) withDO(do gen.Dao) *eventDo {
	e.DO = *do.(*gen.DO)
	return e
}
