// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb-itai/dal/model"
)

func newMinionAccount(db *gorm.DB, opts ...gen.DOOption) minionAccount {
	_minionAccount := minionAccount{}

	_minionAccount.minionAccountDo.UseDB(db, opts...)
	_minionAccount.minionAccountDo.UseModel(&model.MinionAccount{})

	tableName := _minionAccount.minionAccountDo.TableName()
	_minionAccount.ALL = field.NewAsterisk(tableName)
	_minionAccount.ID = field.NewInt64(tableName, "id")
	_minionAccount.MinionID = field.NewInt64(tableName, "minion_id")
	_minionAccount.Inet = field.NewString(tableName, "inet")
	_minionAccount.Name = field.NewString(tableName, "name")
	_minionAccount.LoginName = field.NewString(tableName, "login_name")
	_minionAccount.UID = field.NewString(tableName, "uid")
	_minionAccount.GID = field.NewString(tableName, "gid")
	_minionAccount.HomeDir = field.NewString(tableName, "home_dir")
	_minionAccount.Description = field.NewString(tableName, "description")
	_minionAccount.Status = field.NewString(tableName, "status")
	_minionAccount.Raw = field.NewString(tableName, "raw")
	_minionAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_minionAccount.UpdatedAt = field.NewTime(tableName, "updated_at")

	_minionAccount.fillFieldMap()

	return _minionAccount
}

type minionAccount struct {
	minionAccountDo minionAccountDo

	ALL         field.Asterisk
	ID          field.Int64
	MinionID    field.Int64
	Inet        field.String
	Name        field.String
	LoginName   field.String
	UID         field.String
	GID         field.String
	HomeDir     field.String
	Description field.String
	Status      field.String
	Raw         field.String
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m minionAccount) Table(newTableName string) *minionAccount {
	m.minionAccountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m minionAccount) As(alias string) *minionAccount {
	m.minionAccountDo.DO = *(m.minionAccountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *minionAccount) updateTableName(table string) *minionAccount {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MinionID = field.NewInt64(table, "minion_id")
	m.Inet = field.NewString(table, "inet")
	m.Name = field.NewString(table, "name")
	m.LoginName = field.NewString(table, "login_name")
	m.UID = field.NewString(table, "uid")
	m.GID = field.NewString(table, "gid")
	m.HomeDir = field.NewString(table, "home_dir")
	m.Description = field.NewString(table, "description")
	m.Status = field.NewString(table, "status")
	m.Raw = field.NewString(table, "raw")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *minionAccount) WithContext(ctx context.Context) *minionAccountDo {
	return m.minionAccountDo.WithContext(ctx)
}

func (m minionAccount) TableName() string { return m.minionAccountDo.TableName() }

func (m minionAccount) Alias() string { return m.minionAccountDo.Alias() }

func (m minionAccount) Columns(cols ...field.Expr) gen.Columns {
	return m.minionAccountDo.Columns(cols...)
}

func (m *minionAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *minionAccount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 13)
	m.fieldMap["id"] = m.ID
	m.fieldMap["minion_id"] = m.MinionID
	m.fieldMap["inet"] = m.Inet
	m.fieldMap["name"] = m.Name
	m.fieldMap["login_name"] = m.LoginName
	m.fieldMap["uid"] = m.UID
	m.fieldMap["gid"] = m.GID
	m.fieldMap["home_dir"] = m.HomeDir
	m.fieldMap["description"] = m.Description
	m.fieldMap["status"] = m.Status
	m.fieldMap["raw"] = m.Raw
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m minionAccount) clone(db *gorm.DB) minionAccount {
	m.minionAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m minionAccount) replaceDB(db *gorm.DB) minionAccount {
	m.minionAccountDo.ReplaceDB(db)
	return m
}

type minionAccountDo struct{ gen.DO }

func (m minionAccountDo) Debug() *minionAccountDo {
	return m.withDO(m.DO.Debug())
}

func (m minionAccountDo) WithContext(ctx context.Context) *minionAccountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m minionAccountDo) ReadDB() *minionAccountDo {
	return m.Clauses(dbresolver.Read)
}

func (m minionAccountDo) WriteDB() *minionAccountDo {
	return m.Clauses(dbresolver.Write)
}

func (m minionAccountDo) Session(config *gorm.Session) *minionAccountDo {
	return m.withDO(m.DO.Session(config))
}

func (m minionAccountDo) Clauses(conds ...clause.Expression) *minionAccountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m minionAccountDo) Returning(value interface{}, columns ...string) *minionAccountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m minionAccountDo) Not(conds ...gen.Condition) *minionAccountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m minionAccountDo) Or(conds ...gen.Condition) *minionAccountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m minionAccountDo) Select(conds ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m minionAccountDo) Where(conds ...gen.Condition) *minionAccountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m minionAccountDo) Order(conds ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m minionAccountDo) Distinct(cols ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m minionAccountDo) Omit(cols ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m minionAccountDo) Join(table schema.Tabler, on ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m minionAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m minionAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m minionAccountDo) Group(cols ...field.Expr) *minionAccountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m minionAccountDo) Having(conds ...gen.Condition) *minionAccountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m minionAccountDo) Limit(limit int) *minionAccountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m minionAccountDo) Offset(offset int) *minionAccountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m minionAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *minionAccountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m minionAccountDo) Unscoped() *minionAccountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m minionAccountDo) Create(values ...*model.MinionAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m minionAccountDo) CreateInBatches(values []*model.MinionAccount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m minionAccountDo) Save(values ...*model.MinionAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m minionAccountDo) First() (*model.MinionAccount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionAccount), nil
	}
}

func (m minionAccountDo) Take() (*model.MinionAccount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionAccount), nil
	}
}

func (m minionAccountDo) Last() (*model.MinionAccount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionAccount), nil
	}
}

func (m minionAccountDo) Find() ([]*model.MinionAccount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MinionAccount), err
}

func (m minionAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MinionAccount, err error) {
	buf := make([]*model.MinionAccount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m minionAccountDo) FindInBatches(result *[]*model.MinionAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m minionAccountDo) Attrs(attrs ...field.AssignExpr) *minionAccountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m minionAccountDo) Assign(attrs ...field.AssignExpr) *minionAccountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m minionAccountDo) Joins(fields ...field.RelationField) *minionAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m minionAccountDo) Preload(fields ...field.RelationField) *minionAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m minionAccountDo) FirstOrInit() (*model.MinionAccount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionAccount), nil
	}
}

func (m minionAccountDo) FirstOrCreate() (*model.MinionAccount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MinionAccount), nil
	}
}

func (m minionAccountDo) FindByPage(offset int, limit int) (result []*model.MinionAccount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m minionAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m minionAccountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m minionAccountDo) Delete(models ...*model.MinionAccount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *minionAccountDo) withDO(do gen.Dao) *minionAccountDo {
	m.DO = *do.(*gen.DO)
	return m
}
