// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb-itai/dal/model"
)

func newRiskDNS(db *gorm.DB, opts ...gen.DOOption) riskDNS {
	_riskDNS := riskDNS{}

	_riskDNS.riskDNSDo.UseDB(db, opts...)
	_riskDNS.riskDNSDo.UseModel(&model.RiskDNS{})

	tableName := _riskDNS.riskDNSDo.TableName()
	_riskDNS.ALL = field.NewAsterisk(tableName)
	_riskDNS.ID = field.NewInt64(tableName, "id")
	_riskDNS.Domain = field.NewString(tableName, "domain")
	_riskDNS.Kind = field.NewString(tableName, "kind")
	_riskDNS.Origin = field.NewString(tableName, "origin")
	_riskDNS.BeforeAt = field.NewTime(tableName, "before_at")
	_riskDNS.UpdatedAt = field.NewTime(tableName, "updated_at")
	_riskDNS.CreatedAt = field.NewTime(tableName, "created_at")

	_riskDNS.fillFieldMap()

	return _riskDNS
}

type riskDNS struct {
	riskDNSDo riskDNSDo

	ALL       field.Asterisk
	ID        field.Int64
	Domain    field.String
	Kind      field.String
	Origin    field.String
	BeforeAt  field.Time
	UpdatedAt field.Time
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r riskDNS) Table(newTableName string) *riskDNS {
	r.riskDNSDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r riskDNS) As(alias string) *riskDNS {
	r.riskDNSDo.DO = *(r.riskDNSDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *riskDNS) updateTableName(table string) *riskDNS {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Domain = field.NewString(table, "domain")
	r.Kind = field.NewString(table, "kind")
	r.Origin = field.NewString(table, "origin")
	r.BeforeAt = field.NewTime(table, "before_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *riskDNS) WithContext(ctx context.Context) *riskDNSDo { return r.riskDNSDo.WithContext(ctx) }

func (r riskDNS) TableName() string { return r.riskDNSDo.TableName() }

func (r riskDNS) Alias() string { return r.riskDNSDo.Alias() }

func (r riskDNS) Columns(cols ...field.Expr) gen.Columns { return r.riskDNSDo.Columns(cols...) }

func (r *riskDNS) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *riskDNS) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["domain"] = r.Domain
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["origin"] = r.Origin
	r.fieldMap["before_at"] = r.BeforeAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r riskDNS) clone(db *gorm.DB) riskDNS {
	r.riskDNSDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r riskDNS) replaceDB(db *gorm.DB) riskDNS {
	r.riskDNSDo.ReplaceDB(db)
	return r
}

type riskDNSDo struct{ gen.DO }

func (r riskDNSDo) Debug() *riskDNSDo {
	return r.withDO(r.DO.Debug())
}

func (r riskDNSDo) WithContext(ctx context.Context) *riskDNSDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r riskDNSDo) ReadDB() *riskDNSDo {
	return r.Clauses(dbresolver.Read)
}

func (r riskDNSDo) WriteDB() *riskDNSDo {
	return r.Clauses(dbresolver.Write)
}

func (r riskDNSDo) Session(config *gorm.Session) *riskDNSDo {
	return r.withDO(r.DO.Session(config))
}

func (r riskDNSDo) Clauses(conds ...clause.Expression) *riskDNSDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r riskDNSDo) Returning(value interface{}, columns ...string) *riskDNSDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r riskDNSDo) Not(conds ...gen.Condition) *riskDNSDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r riskDNSDo) Or(conds ...gen.Condition) *riskDNSDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r riskDNSDo) Select(conds ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r riskDNSDo) Where(conds ...gen.Condition) *riskDNSDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r riskDNSDo) Order(conds ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r riskDNSDo) Distinct(cols ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r riskDNSDo) Omit(cols ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r riskDNSDo) Join(table schema.Tabler, on ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r riskDNSDo) LeftJoin(table schema.Tabler, on ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r riskDNSDo) RightJoin(table schema.Tabler, on ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r riskDNSDo) Group(cols ...field.Expr) *riskDNSDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r riskDNSDo) Having(conds ...gen.Condition) *riskDNSDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r riskDNSDo) Limit(limit int) *riskDNSDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r riskDNSDo) Offset(offset int) *riskDNSDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r riskDNSDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *riskDNSDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r riskDNSDo) Unscoped() *riskDNSDo {
	return r.withDO(r.DO.Unscoped())
}

func (r riskDNSDo) Create(values ...*model.RiskDNS) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r riskDNSDo) CreateInBatches(values []*model.RiskDNS, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r riskDNSDo) Save(values ...*model.RiskDNS) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r riskDNSDo) First() (*model.RiskDNS, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Take() (*model.RiskDNS, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Last() (*model.RiskDNS, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) Find() ([]*model.RiskDNS, error) {
	result, err := r.DO.Find()
	return result.([]*model.RiskDNS), err
}

func (r riskDNSDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RiskDNS, err error) {
	buf := make([]*model.RiskDNS, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r riskDNSDo) FindInBatches(result *[]*model.RiskDNS, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r riskDNSDo) Attrs(attrs ...field.AssignExpr) *riskDNSDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r riskDNSDo) Assign(attrs ...field.AssignExpr) *riskDNSDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r riskDNSDo) Joins(fields ...field.RelationField) *riskDNSDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r riskDNSDo) Preload(fields ...field.RelationField) *riskDNSDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r riskDNSDo) FirstOrInit() (*model.RiskDNS, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) FirstOrCreate() (*model.RiskDNS, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskDNS), nil
	}
}

func (r riskDNSDo) FindByPage(offset int, limit int) (result []*model.RiskDNS, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r riskDNSDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r riskDNSDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r riskDNSDo) Delete(models ...*model.RiskDNS) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *riskDNSDo) withDO(do gen.Dao) *riskDNSDo {
	r.DO = *do.(*gen.DO)
	return r
}
