// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/vela-ssoc/vela-common-mb-itai/dal/model"
)

func newRiskIP(db *gorm.DB, opts ...gen.DOOption) riskIP {
	_riskIP := riskIP{}

	_riskIP.riskIPDo.UseDB(db, opts...)
	_riskIP.riskIPDo.UseModel(&model.RiskIP{})

	tableName := _riskIP.riskIPDo.TableName()
	_riskIP.ALL = field.NewAsterisk(tableName)
	_riskIP.ID = field.NewInt64(tableName, "id")
	_riskIP.IP = field.NewString(tableName, "ip")
	_riskIP.Kind = field.NewString(tableName, "kind")
	_riskIP.Origin = field.NewString(tableName, "origin")
	_riskIP.BeforeAt = field.NewTime(tableName, "before_at")
	_riskIP.CreatedAt = field.NewTime(tableName, "created_at")
	_riskIP.UpdatedAt = field.NewTime(tableName, "updated_at")

	_riskIP.fillFieldMap()

	return _riskIP
}

type riskIP struct {
	riskIPDo riskIPDo

	ALL       field.Asterisk
	ID        field.Int64
	IP        field.String
	Kind      field.String
	Origin    field.String
	BeforeAt  field.Time
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r riskIP) Table(newTableName string) *riskIP {
	r.riskIPDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r riskIP) As(alias string) *riskIP {
	r.riskIPDo.DO = *(r.riskIPDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *riskIP) updateTableName(table string) *riskIP {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.IP = field.NewString(table, "ip")
	r.Kind = field.NewString(table, "kind")
	r.Origin = field.NewString(table, "origin")
	r.BeforeAt = field.NewTime(table, "before_at")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *riskIP) WithContext(ctx context.Context) *riskIPDo { return r.riskIPDo.WithContext(ctx) }

func (r riskIP) TableName() string { return r.riskIPDo.TableName() }

func (r riskIP) Alias() string { return r.riskIPDo.Alias() }

func (r riskIP) Columns(cols ...field.Expr) gen.Columns { return r.riskIPDo.Columns(cols...) }

func (r *riskIP) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *riskIP) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["ip"] = r.IP
	r.fieldMap["kind"] = r.Kind
	r.fieldMap["origin"] = r.Origin
	r.fieldMap["before_at"] = r.BeforeAt
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r riskIP) clone(db *gorm.DB) riskIP {
	r.riskIPDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r riskIP) replaceDB(db *gorm.DB) riskIP {
	r.riskIPDo.ReplaceDB(db)
	return r
}

type riskIPDo struct{ gen.DO }

func (r riskIPDo) Debug() *riskIPDo {
	return r.withDO(r.DO.Debug())
}

func (r riskIPDo) WithContext(ctx context.Context) *riskIPDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r riskIPDo) ReadDB() *riskIPDo {
	return r.Clauses(dbresolver.Read)
}

func (r riskIPDo) WriteDB() *riskIPDo {
	return r.Clauses(dbresolver.Write)
}

func (r riskIPDo) Session(config *gorm.Session) *riskIPDo {
	return r.withDO(r.DO.Session(config))
}

func (r riskIPDo) Clauses(conds ...clause.Expression) *riskIPDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r riskIPDo) Returning(value interface{}, columns ...string) *riskIPDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r riskIPDo) Not(conds ...gen.Condition) *riskIPDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r riskIPDo) Or(conds ...gen.Condition) *riskIPDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r riskIPDo) Select(conds ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r riskIPDo) Where(conds ...gen.Condition) *riskIPDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r riskIPDo) Order(conds ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r riskIPDo) Distinct(cols ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r riskIPDo) Omit(cols ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r riskIPDo) Join(table schema.Tabler, on ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r riskIPDo) LeftJoin(table schema.Tabler, on ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r riskIPDo) RightJoin(table schema.Tabler, on ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r riskIPDo) Group(cols ...field.Expr) *riskIPDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r riskIPDo) Having(conds ...gen.Condition) *riskIPDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r riskIPDo) Limit(limit int) *riskIPDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r riskIPDo) Offset(offset int) *riskIPDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r riskIPDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *riskIPDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r riskIPDo) Unscoped() *riskIPDo {
	return r.withDO(r.DO.Unscoped())
}

func (r riskIPDo) Create(values ...*model.RiskIP) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r riskIPDo) CreateInBatches(values []*model.RiskIP, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r riskIPDo) Save(values ...*model.RiskIP) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r riskIPDo) First() (*model.RiskIP, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskIP), nil
	}
}

func (r riskIPDo) Take() (*model.RiskIP, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskIP), nil
	}
}

func (r riskIPDo) Last() (*model.RiskIP, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskIP), nil
	}
}

func (r riskIPDo) Find() ([]*model.RiskIP, error) {
	result, err := r.DO.Find()
	return result.([]*model.RiskIP), err
}

func (r riskIPDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RiskIP, err error) {
	buf := make([]*model.RiskIP, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r riskIPDo) FindInBatches(result *[]*model.RiskIP, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r riskIPDo) Attrs(attrs ...field.AssignExpr) *riskIPDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r riskIPDo) Assign(attrs ...field.AssignExpr) *riskIPDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r riskIPDo) Joins(fields ...field.RelationField) *riskIPDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r riskIPDo) Preload(fields ...field.RelationField) *riskIPDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r riskIPDo) FirstOrInit() (*model.RiskIP, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskIP), nil
	}
}

func (r riskIPDo) FirstOrCreate() (*model.RiskIP, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RiskIP), nil
	}
}

func (r riskIPDo) FindByPage(offset int, limit int) (result []*model.RiskIP, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r riskIPDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r riskIPDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r riskIPDo) Delete(models ...*model.RiskIP) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *riskIPDo) withDO(do gen.Dao) *riskIPDo {
	r.DO = *do.(*gen.DO)
	return r
}
